image: docker:git

services:
  - docker:dind

variables:
  IMAGE: $CI_REGISTRY/andreas/suedtirol1-tracker
  DOCKER_SERVICE_NAME: suedtirol1-tracker

stages:
  - build
  - retag-old-image
  - deploy
  - remove-old-image

build:
  stage: build
  only:
    - master
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $IMAGE:latest || true
    - docker pull $IMAGE:build-stage || true
    - docker build --target build-stage --cache-from $IMAGE:build-stage -t $IMAGE:build-stage .
    - docker build --target runtime-stage --cache-from $IMAGE:build-stage --cache-from $IMAGE:latest -t $IMAGE:latest -t $IMAGE:latest .
    - docker push $IMAGE:latest
    - docker push $IMAGE:build-stage

retag-old-image:
  stage: retag-old-image
  only:
    - master
  before_script:
    - mkdir -p /root/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
  script:
    - RETAG="docker tag $IMAGE:latest $IMAGE:old || true"
    - ssh -p $SSH_PORT -i /root/.ssh/id_rsa -o UserKnownHostsFile=${SSH_KNOWN_HOSTS} ${SSH_USER}@${SERVER_URL} "$RETAG"

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - mkdir -p /root/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
  script:
    - LOGIN="docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
    - PULL="docker-compose -f andreas-compose.yml pull --quiet"
    - BUILD="docker-compose -f andreas-compose.yml up -d $DOCKER_SERVICE_NAME"
    - ssh -p $SSH_PORT -i /root/.ssh/id_rsa -o UserKnownHostsFile=${SSH_KNOWN_HOSTS} ${SSH_USER}@${SERVER_URL} "$LOGIN && $PULL && $BUILD"

remove-old-image:
  stage: remove-old-image
  only:
    - master
  before_script:
    - mkdir -p /root/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa

  script:
    - REMOVE="docker rmi $IMAGE:old || true"
    - ssh -p $SSH_PORT -i /root/.ssh/id_rsa -o UserKnownHostsFile=${SSH_KNOWN_HOSTS} ${SSH_USER}@${SERVER_URL} "$REMOVE"

